### ISSUE TITLE
CSS comments

### ISSUE THREAD

**Issue by jema28** [fack2/WebRangers-repo#30]
What are top and right referencing here?
https://github.com/fack2/WebRangers-repo/blob/771599c76e8a6f4a3cb878ce0c3ac2a65b340bcb/style.css#L7-L18

I would add this font to the body:
https://github.com/fack2/WebRangers-repo/blob/771599c76e8a6f4a3cb878ce0c3ac2a65b340bcb/style.css#L92-L98

For media queries, only things that change need to be added. Does this make sense?
https://github.com/fack2/WebRangers-repo/blob/771599c76e8a6f4a3cb878ce0c3ac2a65b340bcb/style.css#L226-L247

Why are you using float here?
https://github.com/fack2/WebRangers-repo/blob/771599c76e8a6f4a3cb878ce0c3ac2a65b340bcb/style.css#L303-L313

Text is black by default so I would remove the color property here:
https://github.com/fack2/WebRangers-repo/blob/771599c76e8a6f4a3cb878ce0c3ac2a65b340bcb/style.css#L322-L329

**Comment by sulieman1** [comment]
Top and right deleted.
new font added to the body.
removed extra CSS from media-queries.

Why are you using float here?
To be honest our CSS is messed up, Float here makes "Skill" items further apart from each other, I don't know how this works because I didn't work on it, but I'll look at the CSS document and try to figure out why.

color: black removed!

**Comment by sulieman1** [comment]
@jema28
